<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-06-13 04:06

from django.db import migrations
=======
# Generated by Django 3.0.7 on 2020-06-29 07:01

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 750569be8370ed206f930d91d6e8d31fd4a2e3a8


class Migration(migrations.Migration):

<<<<<<< HEAD
=======
    initial = True

>>>>>>> 750569be8370ed206f930d91d6e8d31fd4a2e3a8
    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grade')),
            ],
        ),
>>>>>>> 750569be8370ed206f930d91d6e8d31fd4a2e3a8
    ]
