# Generated by Django 3.0.8 on 2020-07-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200622_2232'),
        ('app', '0002_auto_20200629_1504'),
    ]

    operations = [
    ]
